### ISSUE TITLE
Wrogowie

### ISSUE THREAD

**Issue by naitoramu** [dkwapisz/PlatformGameUnity#2]
Stworzenie i rozwój modeli oraz mechanik związanych z wrogami.

**Comment by agnieszkowe** [comment]
https://assetstore.unity.com/packages/2d/characters/bringer-of-death-free-195719

https://assetstore.unity.com/packages/2d/characters/enemy-galore-1-pixel-art-208921

https://assetstore.unity.com/packages/2d/characters/bandits-pixel-art-104130
