### ISSUE TITLE
Scena - poprawa ułożenia elementów

### ISSUE THREAD

**Issue by naitoramu** [dkwapisz/PlatformGameUnity#3]
Poprawa przestrzeni do walk z bossami
Poprawa plaftorm tak aby dało się skakać po nich

**Comment by agnieszkowe** [comment]
https://assetstore.unity.com/packages/2d/textures-materials/tiles/2d-basic-platformer-pack-110887

https://assetstore.unity.com/packages/2d/characters/sunny-land-103349

https://assetstore.unity.com/packages/2d/textures-materials/tiles/parallax-dusk-mountain-background-53403

https://assetstore.unity.com/packages/2d/environments/free-platform-game-assets-85838
