### ISSUE TITLE
Podstawowa mechanika aktora

### ISSUE THREAD

**Issue by naitoramu** [dkwapisz/PlatformGameUnity#4]
#1 
Stworzenie podstawowych mechanik związanych z aktorem.

**Comment by dkwapisz** [comment]
Aktualna implementacja:
- poruszanie się prawo lewo -> A, D, Strzałki prawo lewo
- kucanie - S, strzałka w dół
- skakanie - Spacja 

ToDo:
- zrobić tak, aby gracz nie zawieszał się na ścianie, gdy na nią wskakuje i napiera (musi się ześlizgiwać)

**Comment by dkwapisz** [comment]
Gracz ześlizguje się ze ściany (nie przykleja się do niej) -> służy do tego plik Player Physics 2D i parametr Friction = 0.
