### ISSUE TITLE
Model gracza

### ISSUE THREAD

**Issue by naitoramu** [dkwapisz/PlatformGameUnity#5]
#1 
Stworzenie i przetestowanie działącego graficznego modelu gracza

**Comment by agnieszkowe** [comment]
https://assetstore.unity.com/packages/2d/characters/cute-2d-college-student-198684

https://assetstore.unity.com/packages/2d/characters/cute-2d-girl-wizard-155796

https://assetstore.unity.com/packages/2d/characters/cute-2d-girl-kindergartner-187534

https://assetstore.unity.com/packages/2d/characters/warrior-free-asset-195707 (to ma dużo opcji np crouch)
