### ISSUE TITLE
Muzyka i podstawowe sfx

### ISSUE THREAD

**Issue by dkwapisz** [dkwapisz/PlatformGameUnity#64]
Dodać muzykę i podstawowe efekty dźwiękowe. Niekrytyczne, ale fajnie jakby było.

**Comment by michpil19** [comment]
Propozycje muzyki w tle:
https://youtu.be/OPj6UwaYvUE - Opus No. 1 REMIX // cisco phone hold music - guitar
Walka z bossem:

Efekty  z asset stora FREE:
